In [12]:
import pandas as pd

# Total data

In [13]:
df = pd.read_csv('../data/taxi_trips_2019.csv', parse_dates=['Trip Start Timestamp'])
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16477365 entries, 0 to 16477364
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Trip ID                     object
 1   Taxi ID                     object
 2   Trip Start Timestamp        datetime64[ns]
 3   Trip End Timestamp          object
 4   Trip Seconds                float64
 5   Trip Miles                  float64
 6   Pickup Census Tract         float64
 7   Dropoff Census Tract        float64
 8   Pickup Community Area       float64
 9   Dropoff Community Area      float64
 10  Fare                        float64
 11  Tips                        float64
 12  Tolls                       float64
 13  Extras                      float64
 14  Trip Total                  float64
 15  Payment Type                object
 16  Company                     object
 17  Pickup Centroid Latitude    float64
 18  Pickup Centroid Longitude   float64
 19  Pickup Centroid Location    object
 20  Dropoff Centroid Latitude   float64
 21  Dropoff Centroid Longitude  float64
 22  Dropoff Centroid  Location  object
dtypes: datetime64[ns](1), float64(15), object(7)
memory usage: 2.8+ GB

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,...,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
0,f24ef1302cd672bbcbeb7dbc60ef78dceeb138b7,1801165e22d31b0d2557544664d5ac37511b6cd2972126...,2019-01-01,01/01/2019 12:15:00 AM,885.0,3.45,NaN,NaN,NaN,NaN,...,4.0,16.75,Cash,Flash Cab,NaN,NaN,NaN,NaN,NaN,NaN
1,8e40b9c59af7b2897dc7a1163c472903e0dd6e9a,7a387c4ea03aea6f051c2083737fa232315f8dad35cf36...,2019-01-01,01/01/2019 12:00:00 AM,8.0,0.00,NaN,NaN,NaN,NaN,...,0.0,3.25,Cash,Chicago Carriage Cab Corp,NaN,NaN,NaN,NaN,NaN,NaN
2,189631d3891a33361d68ef460c2d3049179f9837,d1d781b6807176ed53fbb9d0010dd0a87e29c073984bda...,2019-01-01,01/01/2019 12:15:00 AM,960.0,4.90,NaN,NaN,NaN,NaN,...,1.0,20.10,Credit Card,Star North Management LLC,NaN,NaN,NaN,NaN,NaN,NaN
3,e4941ac16f2fccf07218d2656a056103a4bf64a6,6933327f9cc740e893a882282f7d06460207d6d4e084b3...,2019-01-01,01/01/2019 12:00:00 AM,420.0,1.50,NaN,NaN,NaN,NaN,...,0.0,7.50,Cash,Star North Management LLC,NaN,NaN,NaN,NaN,NaN,NaN
4,57a104b6cf260f117de051e61193e806ceb0f347,6933327f9cc740e893a882282f7d06460207d6d4e084b3...,2019-01-01,01/01/2019 12:15:00 AM,420.0,0.50,NaN,NaN,NaN,NaN,...,1.0,8.00,Credit Card,Star North Management LLC,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.columns

Index(['Trip ID', 'Taxi ID', 'Trip Start Timestamp', 'Trip End Timestamp',
       'Trip Seconds', 'Trip Miles', 'Pickup Census Tract',
       'Dropoff Census Tract', 'Pickup Community Area',
       'Dropoff Community Area', 'Fare', 'Tips', 'Tolls', 'Extras',
       'Trip Total', 'Payment Type', 'Company', 'Pickup Centroid Latitude',
       'Pickup Centroid Longitude', 'Pickup Centroid Location',
       'Dropoff Centroid Latitude', 'Dropoff Centroid Longitude',
       'Dropoff Centroid  Location'],
      dtype='object')

# Trimming data
* Month of May
* Select columns

In [15]:
usecols = ['Taxi ID', 'Trip Start Timestamp', 'Trip End Timestamp',
       'Trip Miles', 'Trip Total', 'Pickup Centroid Location',
       'Dropoff Centroid  Location']

df[df['Trip Start Timestamp'].dt.month == 4][usecols].to_csv('../data/taxi_trips_201905_trimmed.csv', index=False)